cache: .tox

environment:
  SDL_VIDEODRIVER: dummy

  AWS_ACCESS_KEY_ID:
    secure: 3BNx+Qb95vjwu5E6CbX9mrQ8X4EboF4dzt9Ei7Wc4QU=

  AWS_SECRET_ACCESS_KEY:
    secure: bkPtYZvL3Asozn/udXEZChW2gqT/GEJ66xdf+OeMtn4faZR36uKoP2x+wgCp0enQ

  matrix:
    # - job_name: Tests Windows
    #   job_group: Tests
    #   appveyor_build_worker_image: Visual Studio 2019
    #
    # - job_name: Tests macOS
    #   job_group: Tests
    #   appveyor_build_worker_image: macOS

    - job_name: Deploy
      job_depends_on: Tests
      appveyor_build_worker_image: macOS

matrix:
  fast_finish: true

build: off

for:
  -
    matrix:
      only:
        - job_name: Tests Windows

    install:
      - pip install tox

    test_script:
      - python -m tox

  -
    matrix:
      only:
        - job_name: Tests macOS

    install:
      - pip install tox

    before_test:
      - export PATH=$PATH:~/venv3.5/bin/:~/venv3.6/bin/:~/venv3.7/bin/:~/venv3.8/bin/

    test_script:
      - python -m tox

  -
    matrix:
      only:
        - job_name: Deploy

    install:
      - export PATH=$PATH:~/venv3.8/bin/
      - cd build
      - ./release.sh
