cache: .tox

environment:
  SDL_VIDEODRIVER: dummy
  matrix:
    - job_name: Tests Windows
      job_group: Tests
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: Tests macOS
      job_group: Tests
      appveyor_build_worker_image: macOS

    - job_name: Deploy
      job_depends_on: Tests
      appveyor_build_worker_image: macOS

matrix:
  fast_finish: true

build: off

for:
  -
    matrix:
      only:
        - job_group: Tests

    install:
      - pip install tox

    test_script:
      - python -m tox

  -
    matrix:
      only:
        - job_name: Tests macOS

    before_test:
      - export PATH=$PATH:~/venv3.5/bin/:~/venv3.6/bin/:~/venv3.7/bin/:~/venv3.8/bin/

  -
    matrix:
      only:
        - job_name: Deploy

    before_deploy:
      - cd build
      - ./release.sh
