image:
  - Visual Studio 2019
  - macOS

cache: .tox

environment:
  SDL_VIDEODRIVER: dummy
  matrix:
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38

for:
-
  matrix:
    only:
      - image: macOS

  before_test:
    - export PATH=$PATH:~/venv3.5/bin/:~/venv3.6/bin/:~/venv3.7/bin/:~/venv3.8/bin/

build: off

install:
  - pip install tox

test_script:
  - python -m tox
