image:
  - Visual Studio 2019
  - macOS

cache: .tox

environment:
  SDL_VIDEODRIVER: dummy
  matrix:
    # - TOXENV: py35
    # - TOXENV: py36
    # - TOXENV: py37
    - TOXENV: py38

build: off

install:
  - pip install tox

test_script:
  - python -m tox
