[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend="setuptools.build_meta"

[tool.ruff]
exclude = ["cmu_graphics/libs"]
src = ["cmu_graphics"]


[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.per-file-ignores]
"cmu_graphics/*" = ["F401", "E402"]
