[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend="setuptools.build_meta"

[tool.ruff]
exclude = ["cmu_graphics/libs"]
src = ["cmu_graphics"]

[tool.ruff.format]
quote-style = "single"
